version: '3'

services:

  web:
    build: .
    ports:
      - "127.0.0.1:3050:3050"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=172.17.0.1
      - REDIS_PORT=6380
    extra_hosts:
      - "host.docker.internal:host-gateway"
      